using CommandLine;

namespace TopicStream.Infrastructure.CommandLine;

/// <summary>
/// Command line options for the deployment stack
/// </summary>
internal class CommandLineOptions
{
  /// <summary>
  /// An id for the stack. This will be prefixed to resource names to support multiple instances
  /// of the stack in one environment. If not provided, no resource prefix will be given to resources.
  /// This is the happy-medium between automatic suffixes generated by the CDK (not user-friendly, but always unique)
  /// and no unique id at all (user-friendly, but limits each AWS account to only one instance of the system).
  /// </summary>
  [Option(
    "stack-id",
    Required = false,
    Default = "TopicStream",
    HelpText = "An id for the stack. This will be included resource names to support multiple instances of the stack in one environment"
  )]
  public required string StackId { get; set; }

  /// <summary>
  /// The path to the project that holds Lambda function code; this allows running from any working directory
  /// without assuming the relative path to the Lambda functions project. The default assumes we're running
  /// from within the TopicStream.Infrastructure project directory.
  /// </summary>
  [Option(
    "functions-project",
    Required = false,
    Default = "../TopicStream.Functions",
    HelpText = "The path to the project that holds Lambda function code."
  )]
  public required string FunctionsProject { get; set; }
}